- templates/commands/render_test.go
- templates/model/spec.go
- templates/model/spec_test.go
- templates/model/validate.go
Currently each field has only one valid value, so this is simple.
> Validate apiVersion and kind spec fields

- README.md
The existing docs are for users of the CLI; the new docs are for people that are creating templates to be used by others.
> Add template developer docs to the README

- templates/commands/render_action.go
- templates/commands/render_action_gotemplate_test.go
> feat: add go template functions

- templates/commands/render_action.go
- templates/commands/render_action_test.go
These error messages printed the wrong variable :/
Closes #57.
> Trivial fix of error message

- templates/commands/render_action_gotemplate.go
- templates/commands/render_action_gotemplate_test.go
> fix: allow template expressions in go_template paths

- .github/workflows/release.yml
This time we're following the docs from
https://github.com/goreleaser/goreleaser-action.
> Fix goreleaser permission error

- .github/workflows/release.yml
I missed this part of the example :(
> Fix goreleaser permission issue 3rd try

- .github/workflows/lint-test.yml
- .goreleaser.yaml
- templates/commands/render.go
- templates/commands/render_action_include_test.go
- templates/commands/render_action_test.go
- templates/commands/render_test.go
Fixes https://github.com/abcxyz/abc/issues/70
> Add support for Windows

- .github/workflows/release.yml
Copied from lumberjack/jvs/gma, which also do this.
> Do a release when a v* tag is pushed

- templates/commands/render.go
- templates/commands/render_action.go
Quick follow-up of https://github.com/abcxyz/abc/pull/102, this uses structured KV pairs instead of string interpolation.
> Use structured logging instead

- README.md
- RELEASING.md
> Instructions for releasing and downloading

- templates/commands/render_action.go
- templates/commands/render_action_test.go
Add snake case functions to the template rendering functions, per https://github.com/abcxyz/terraform-modules/pull/42#discussion_r1280185644
> feat: template functions for snake_case

- templates/commands/render_action.go
- templates/commands/render_action_test.go
- templates/commands/template_funcs.go
- templates/commands/template_funcs_test.go
Closes https://github.com/abcxyz/abc/issues/126
> Add sortStrings template functions

- t/react_template/.github/config/autopush.env
- t/react_template/.github/workflows/deploy.yaml
- t/react_template/spec.yaml
- t/react_template/src/App.tsx
In preparation for demo - Aug 17
> Update react_template with deployment workflow, backend URL

- go.mod
- go.sum
- internal/version/version.go
I'm 99.9% certain this will work 😄
> Switch to buildinfo package

- README.md
This is the final PR for `for_each`. Closes #127.
> Document `for_each` and CEL

- README.md
Somehow these were never documented.
> Add docs for template inputs

- README.md
- templates/common/cel.go
- templates/common/cel_test.go
For #39.
We recently added the input validation feature and custom CEL function to support it. Now the docs are caught up with the code.
Also add some new test cases that just occurred to me.
> Add docs for custom CEL functions and input validation

- README.md
Should've been part of https://github.com/abcxyz/abc/pull/201 but was overlooked.
> update readme to remove strip/add prefix

- templates/commands/render/action.go
- templates/commands/render/render.go
Fix unintended logging outputs when running CLI commands.
> Change logger.InfoContext -> DebugContext

- templates/commands/goldentest/record.go
- templates/commands/goldentest/record_test.go
- templates/commands/goldentest/test_funcs.go
- templates/commands/goldentest/test_funcs_test.go
- templates/commands/render/action_append_test.go
- templates/commands/render/action_gotemplate_test.go
- templates/commands/render/action_include.go
- templates/commands/render/action_include_test.go
- templates/commands/render/action_regexnamelookup_test.go
- templates/commands/render/action_regexreplace_test.go
- templates/commands/render/action_stringreplace_test.go
- templates/commands/render/action_test.go
- templates/commands/render/render_test.go
- templates/common/test_utils.go
Will add test.yaml version check in a separated PR.
> Add golden test render command implementations.

- templates/commands/render/action.go
- templates/commands/render/action_append_test.go
- templates/commands/render/action_gotemplate_test.go
- templates/commands/render/action_include.go
- templates/commands/render/action_include_test.go
- templates/commands/render/action_regexnamelookup_test.go
- templates/commands/render/action_regexreplace_test.go
- templates/commands/render/action_stringreplace_test.go
- templates/commands/render/action_test.go
- templates/commands/render/render.go
- templates/commands/render/render_test.go
- templates/common/abstract_fs.go
- templates/common/fs.go
Simple refactoring - just to move one function.
> Make CopyRecursive reusable for all templates actions.

- templates/commands/goldentest/record.go
- templates/commands/goldentest/record_test.go
- templates/commands/goldentest/test_funcs.go
- templates/commands/goldentest/test_funcs_test.go
... to avoid template output overwrites test.yaml
> Move golden test artifacts from test-case/ to test-case/data/

- README.md
- templates/commands/render/render.go
- templates/commands/render/render_test.go
- templates/model/spec/v1alpha1/spec.go
Also: fix a bug where an error should have been returned but wasn't.
Fixes #220 .
> Add conditional step execution with "if"

- t/react_template/package-lock.json
- t/react_template/package.json
Fix https://github.com/abcxyz/abc/security/dependabot/11
> Upgrade post-css 

- templates/commands/render/flags.go
- templates/commands/render/render.go
- templates/commands/render/render_test.go
> feat: support multi input files

- .github/workflows/lint-test.yml
~⚠️  Requires https://github.com/abcxyz/pkg/pull/237 to be merged first.~ Done!
> Switch from 'on' to 'runs-on' in go-test workflow

- t/flutter_template/README.md
- t/flutter_template/android/app/build.gradle
- t/flutter_template/android/build.gradle
- t/flutter_template/lib/main.dart
- t/flutter_template/lib/screen/landing_screen.dart
- t/flutter_template/lib/screen/login_screen.dart
- t/flutter_template/lib/state/authentication/bloc/authentication_bloc.dart
- t/flutter_template/lib/state/authentication/bloc/authentication_event.dart
- t/flutter_template/lib/state/authentication/bloc/authentication_state.dart
- t/flutter_template/lib/state/authentication/model/user_model.dart
- t/flutter_template/pubspec.lock
- t/flutter_template/pubspec.yaml
- t/flutter_template/spec.yaml
- t/flutter_template/test/widget_test.dart
Same as other FE template, we use Auth0 as required param here. Will make this conditional in the next step.
> Add Auth0 Android implementation and Auth0 template params.

- README.md
add readme for describe command.
Part of the fix for #62
> feat: add readme for describe

- templates/commands/describe/describe.go
- templates/commands/describe/describe_test.go
- templates/commands/render/action_append.go
- templates/commands/render/action_append_test.go
- templates/commands/render/action_foreach.go
- templates/commands/render/action_foreach_test.go
- templates/commands/render/action_gotemplate.go
- templates/commands/render/action_gotemplate_test.go
- templates/commands/render/action_include.go
- templates/commands/render/action_include_test.go
- templates/commands/render/action_print.go
- templates/commands/render/action_print_test.go
- templates/commands/render/action_regexnamelookup.go
- templates/commands/render/action_regexnamelookup_test.go
- templates/commands/render/action_regexreplace.go
- templates/commands/render/action_regexreplace_test.go
- templates/commands/render/action_stringreplace.go
- templates/commands/render/action_stringreplace_test.go
- templates/commands/render/render.go
- templates/commands/render/render_test.go
- templates/common/specutil/spec.go
- templates/common/specutil/spec_test.go
- templates/model/README.md
- templates/model/decode/decode.go
- templates/model/decode/decode_test.go
- templates/model/spec/v1beta1/upgrade.go
- templates/model/spec/v1beta2/spec.go
- templates/model/spec/v1beta2/spec_test.go
- templates/model/spec/v1beta2/upgrade.go
This is intended to be the version where @sqin2019 and @tyroneclay add their new features. When they're ready, we'll actually release this version. I added TODOs so you know where to start hacking.
I'm following the instructions in https://github.com/abcxyz/abc/blob/main/templates/model/README.md.
> Add new work-in-progress unreleased api_version v1beta2

- README.md
- examples/templates/render/for_each_dynamic/testdata/golden/multiple_envs/data/autopush.cfg
- examples/templates/render/for_each_dynamic/testdata/golden/multiple_envs/data/integration.cfg
- examples/templates/render/for_each_dynamic/testdata/golden/multiple_envs/data/prod.cfg
- examples/templates/render/for_each_dynamic/testdata/golden/multiple_envs/test.yaml
- examples/templates/render/for_each_dynamic/testdata/golden/one_env/data/prod.cfg
- examples/templates/render/for_each_dynamic/testdata/golden/one_env/test.yaml
- examples/templates/render/for_each_hardcoded/testdata/golden/render_template/data/dev.cfg
- examples/templates/render/for_each_hardcoded/testdata/golden/render_template/data/production.cfg
- examples/templates/render/for_each_hardcoded/testdata/golden/render_template/test.yaml
resolves https://github.com/abcxyz/abc/issues/35
> Add golden tests to abc template examples.

- README.md
- templates/commands/render/action_foreach.go
- templates/commands/render/flags.go
- templates/commands/render/render.go
- templates/commands/render/render_test.go
- templates/common/flags/flags.go
fix part of #121: Offer the ability to show a diff of changes to each file due to each action
> feat: add debug step diffs flag

- templates/commands/render/manifest.go
- templates/commands/render/manifest_test.go
I simply forgot to write it, then forgot to test that I had written it :/
> fix: template_version was empty in manifest

- templates/commands/describe/describe.go
- templates/commands/describe/describe_test.go
- templates/commands/render/action_append.go
- templates/commands/render/action_append_test.go
- templates/commands/render/action_foreach.go
- templates/commands/render/action_foreach_test.go
- templates/commands/render/action_gotemplate.go
- templates/commands/render/action_gotemplate_test.go
- templates/commands/render/action_include.go
- templates/commands/render/action_include_test.go
- templates/commands/render/action_print.go
- templates/commands/render/action_print_test.go
- templates/commands/render/action_regexnamelookup.go
- templates/commands/render/action_regexnamelookup_test.go
- templates/commands/render/action_regexreplace.go
- templates/commands/render/action_regexreplace_test.go
- templates/commands/render/action_stringreplace.go
- templates/commands/render/action_stringreplace_test.go
- templates/commands/render/render.go
- templates/commands/render/render_test.go
- templates/common/input/input.go
- templates/common/input/input_test.go
- templates/common/specutil/spec.go
- templates/common/specutil/spec_test.go
- templates/model/decode/decode.go
- templates/model/decode/decode_test.go
- templates/model/spec/v1beta2/upgrade.go
- templates/model/spec/v1beta3/spec.go
- templates/model/spec/v1beta3/spec_test.go
- templates/model/spec/v1beta3/upgrade.go
This was done by mechanically following the instructions in https://github.com/abcxyz/abc/blob/main/templates/model/README.md. There's no interesting code here.
> Add new work-in-progress schema v1beta3

- README.md
> Document api_version v1beta2 in preparation for release

- templates/commands/render/action_include_test.go
- templates/commands/render/render_test.go
#323 doesn't seem to apply anymore after file globbing changes.
> Add tests for simple skip (1 file)

- .gitignore
> chore: added gitignore

- README.md
- templates/commands/goldentest/record.go
updated record docs and cli to make golden-test record more clear
> docs: updated record docs and cli to make golden-test record more clear

- templates/common/render/render.go
- templates/common/templatesource/download.go
> chore: clean up unused dest

- templates/commands/goldentest/flags.go
- templates/commands/goldentest/new_test_cli.go
- templates/commands/goldentest/new_test_cli_test.go
- templates/commands/goldentest/new_test_flags.go
- templates/commands/goldentest/record.go
- templates/commands/goldentest/record_test.go
- templates/commands/goldentest/verify.go
- templates/commands/goldentest/verify_test.go
made location as a default positional argument
> feat: made location as a default positional argument

- templates/commands/goldentest/new_test_cli_test.go
- templates/commands/goldentest/record_test.go
- templates/commands/goldentest/verify_test.go
Fixed comment from https://github.com/abcxyz/abc/pull/383#discussion_r1467205091
> fix: fixed error check

- templates/commands/goldentest/new_test_cli.go
- templates/commands/goldentest/new_test_cli_test.go
1. fixed overwrite behavior when the overwrite need to delete some previous contents
> fix: fixed overwrite behavior

- templates/commands/goldentest/new_test_cli.go
- templates/commands/goldentest/new_test_cli_test.go
- templates/common/render/render_test.go
- templates/common/testutil/prompt.go
Add prompt UT in goldentest new-test
> Test: prompt  UT in goldentest new-test

- templates/commands/render/render.go
- templates/commands/render/render_test.go
- templates/common/render/render.go
- templates/common/render/render_test.go
- templates/common/testutil/fs.go
- templates/common/testutil/prompt.go
> Test: added render prompt ut

- templates/commands/goldentest/verify.go
- templates/commands/goldentest/verify_test.go
> chore: adjust error message for golden-test verify

- README.md
> docs: added new-test readme

- examples/templates/render/print/testdata/golden/example/data/.abc/.stdout
- examples/templates/render/print/testdata/golden/no-output-files/data/.abc/.stdout
- t/data_migration_pipeline/testdata/golden/basic/data/.abc/.stdout
- t/react_template/testdata/golden/basic/data/.abc/.stdout
- templates/commands/goldentest/record_test.go
- templates/commands/goldentest/test_funcs.go
- templates/commands/goldentest/test_funcs_test.go
- templates/commands/goldentest/verify.go
- templates/commands/goldentest/verify_test.go
- templates/common/paths.go
> feat: verify stdout in goldentest

- cmd/abc/abc.go
> chore: fixed windows os error msg

- templates/commands/goldentest/test_funcs_test.go
- templates/commands/render/render_test.go
- templates/common/fs_test.go
- templates/common/render/action_include_test.go
- templates/common/render/render_test.go
- templates/testutil/fs.go
removed unused cmp file mode,
fixed https://github.com/abcxyz/abc/pull/412#discussion_r1483536563
> chore: removed cmp file mode

- templates/commands/goldentest/new_test_cli.go
- templates/commands/goldentest/new_test_cli_test.go
- templates/commands/goldentest/record_test.go
- templates/commands/goldentest/record_verify_test.go
- templates/commands/goldentest/test_funcs.go
- templates/commands/goldentest/test_funcs_test.go
- templates/commands/goldentest/verify_test.go
- templates/model/decode/decode.go
- templates/model/decode/decode_test.go
- templates/model/goldentest/v1beta3/upgrade.go
- templates/model/goldentest/v1beta4/goldentest.go
- templates/model/goldentest/v1beta4/goldentest_test.go
- templates/model/goldentest/v1beta4/upgrade.go
fixed part of #428 
1. Upgraded goldentest to v1beta4
2. Added UT to guard unreleased version.
> feat: upgrade goldentest to v1beta4

- templates/model/README.md
> docs: updated upgrade readme

- README.md
> Add README update for tab autocompletion

- examples/templates/render/print/spec.yaml
- examples/templates/render/print/testdata/golden/example/test.yaml
- examples/templates/render/print/testdata/golden/no-output-files/test.yaml
- internal/version/version.go
> fix: fixed release build info

- .github/workflows/notify-on-issue-and-release.yml
I think this should be the fix.
> change trigger

- README.md
> Add missing docs for v1beta5 and top-level rules

- templates/commands/goldentest/new_test_cli.go
- templates/commands/goldentest/verify.go
- templates/commands/goldentest/verify_test.go
> chore: better UX around recording test data

- README.md
- templates/model/decode/decode.go
- templates/model/decode/decode_test.go
This is in preparation for releasing binary version 0.7.
> Mark api_version v1beta6 as ready for release

- templates/common/render/render.go
Reacting to changes in https://github.com/abcxyz/pkg/pull/314
> fix linter errors from latest goalngci upgrade

- templates/common/upgrade/hash.go
- templates/common/upgrade/upgrade.go
This is part of the template upgrades feature. I'm committing in pieces because the entire feature is too big for one PR.
Why are there no tests? I've chosen to test this at the level of the exported API. There are tests already written that will be sent out soon that cover all of the code paths in this PR.
> Add individual file hashing function

- t/react_template/package-lock.json
- t/react_template/testdata/golden/basic/data/package-lock.json
This required manually running `abc templates golden-test record` after applying the dependabot patch.
> Resolve dependabot #493

- examples/templates/render/git_vars/spec.yaml
- examples/templates/render/git_vars/testdata/golden/is_git_no_tag/data/.abc/stdout
- examples/templates/render/git_vars/testdata/golden/is_git_no_tag/data/out.txt
- examples/templates/render/git_vars/testdata/golden/is_git_no_tag/test.yaml
- examples/templates/render/git_vars/testdata/golden/is_git_with_tag/data/.abc/stdout
- examples/templates/render/git_vars/testdata/golden/is_git_with_tag/data/out.txt
- examples/templates/render/git_vars/testdata/golden/is_git_with_tag/test.yaml
- examples/templates/render/git_vars/testdata/golden/not_git/data/.abc/stdout
- examples/templates/render/git_vars/testdata/golden/not_git/data/out.txt
- examples/templates/render/git_vars/testdata/golden/not_git/test.yaml
- examples/templates/render/inputs/spec.yaml
- examples/templates/render/inputs/testdata/golden/example/data/.abc/stdout
- examples/templates/render/inputs/testdata/golden/example/data/out.txt
- examples/templates/render/inputs/testdata/golden/example/test.yaml
> feat: Rewrite examples to print to stdout instead of appending to out.txt

- README.md
updated readme with record all and verify all
> docs: updated readme with record all and verify all

- templates/commands/goldentest/verify.go
https://github.com/abcxyz/abc/pull/542/files#diff-9abbcd7b9d21c113eb79ee4bc0c4c20ea5da1397a5542d849de15375aef28f41R142 is missing the fix.
> fix: fixed code style for common exists

- templates/common/fs.go
We'll soon use CopyFile in the template upgrade operation without a Hash.
There was never really any reason for CopyFile to take a Hash instead of a Writer; a Hash implements the Writer interface.
> Generalize hash to any io.Writer in CopyFile

- .github/workflows/lint-test.yml
> Remove line-ending hack since we don't support windows anymore

- README.md
Perhaps a change significant enough to warrant a release :)
> Removed duplicate word typo in readme.

- cmd/abc/abc.go
- go.mod
- go.sum
Add preceding newline to update notification.
> Update abc-updater for more concise notification.

- t/nextjs_react_template/testdata/golden/basic/data/package-lock.json
- t/react_template/testdata/golden/basic/data/package-lock.json
Recovers from #588 being merged prematurely. It had failing tests.
Separately, I'll work on updating the github config to require passing tests.
> Fix golden tests broken by dependabot

- cmd/abc/abc_test.go
- templates/commands/render/flags.go
- templates/commands/render/render_test.go
We're about to create a release with upgrade support, and we assume that
everyone will want upgradeable template installations.
>  Default --manifest to true

- templates/commands/upgrade/flags.go
This one flag somehow got missed.
> Add missing tab-complete configuration

- .github/workflows/release.yml
Apparently GH Actions doesn't like using " for string literals
> Switch to escaped single quote in gh action

- README.md
- cmd/abc/abc.go
- internal/metricswrap/metrics.go
Copied from changes in guaridan metrics PR.
> Metrics fixes

- templates/commands/upgrade/upgrade.go
This logic was changed a few weeks ago but the instructions werent updated accordingly.
> fix merge conflict instructions

- .github/workflows/create-tag.yml
- .github/workflows/lint-test.yml
Update to use the new actions repo for actions instead of pkg.
> chore: use new actions repo
