templates/commands/render.go, templates/commands/render_test.go
This has two benefits:
- Avoids the awkwardness of a "required flag"
- Makes the command easier to type by skipping the "-s"
=> Make the template source into a positional argument

templates/model/primitive.go, templates/model/spec.go, templates/model/spec_test.go, templates/model/validate.go
This PR adds the remaining action types from the design doc: `regex_replace`, `string_replace`, and `go_template`.
=> Add more action types

templates/commands/render.go, templates/commands/render_action_gotemplate.go, templates/commands/render_action_include.go, templates/commands/render_action_include_test.go, templates/commands/render_action_print.go, templates/commands/render_action_print_test.go, templates/commands/render_action_regexreplace.go, templates/commands/render_action_stringreplace.go, templates/commands/render_test.go, templates/model/pos.go
The "include" action copies files from the template into the scratch directory. This is analogous to a docker "COPY".
The "print" command just prints to stdout.
In both of these actions, template variable substitution is allowed.
This PR is big, but it's mostly tests.
Coming next: implementing more action types and committing the scratch dir to the output directory.
=> Implement the "include" and "print" actions

templates/commands/render.go, templates/commands/render_test.go
The desired behavior is that the scratch dir and template dir are both removed unless the user specifies --keep-temp-dirs. We failed to actually clean up the scratch dir.
There was also an incorrect test where this was supposed to be tested; we incorrectly asserted the oppposite of what we should have. This has been fixed here.
=> Fix a bug causing scratch dir not to be cleaned up

templates/commands/render.go, templates/commands/render_action_include.go, templates/commands/render_action_include_test.go, templates/commands/render_test.go
The logic in this PR is to use `overwrite=true` when writing to the scratch directory. This allows multiple include actions to touch the same set of files, if the template author wishes.
This PR also improves error messages in some edge cases.
This PR also forbids overwriting files with directories and vice versa, because that would be confusing for both template developers and abc code maintainers.
In an upcoming PR, we will set `overwrite=$(value_of_--force_overwrite_flag)` when writing to the final output directory.
=> More detailed logic for when overwriting is OK

templates/commands/render.go, templates/commands/render_action_include.go, templates/commands/render_test.go, templates/model/pos.go, templates/model/pos_test.go
This is the final phase of the the rendering process: taking each file and directory in the scratch dir and copying it into the destination.
We want to make this as atomic as possible. If there are any errors, we want to leave the destination directory untouched. We don't want half of the output files to succeed and half of them to be missing; this would be annoying for users to clean up. To achieve this atomicity, we first do a "dry run" copy that checks whether the copy *would* succeed, then we do a real copy. This could be made more efficient in the future, but it's good enough for now.
In this PR we also switch from ReadFile+WriteFile to io.Copy; it seemed silly to read a buffer then just write it again.
=> Copy the scratch dir contents to the dest dir

templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_include.go, templates/commands/render_action_stringreplace.go, templates/commands/render_action_stringreplace_test.go, templates/commands/render_action_test.go, templates/commands/render_test.go, templates/model/spec.go, templates/model/spec_test.go
This is an action that performs a straightforward string replacement on a list of paths (either directories or files). Template variables can be used when specifying any of the parameters:
- paths in which to replace
- strings to be replaced
- strings to be used as replacements.
Most of the logic is in the walkAndModify() function, and the string replacement logic is a thin wrapper around it. This lays the foundation for actionRegexReplace() and actionGoTemplate() to also use walkAndModify().
=> Add the stringreplace action

examples/templates/render/hello_jupiter/spec.yaml
- Update apiVersion to the new format, the old format is now rejected
- Fix bad indentation that prevented the example from rendering
- Autoformat the whole file with `prettier` (hopefully yamllint is OK with this)
=> Fix broken example and autoformat

README.md, templates/commands/render_action_regexreplace.go, templates/commands/render_action_regexreplace_test.go, templates/model/spec.go, templates/model/spec_test.go, templates/model/validate.go
To make sure our template spec files are maintainable, we force the use of named subgroups (eg `(?P<mygroup>re`) rather than numbered subgroups (eg `(re)`). Correspondingly we force the replacement strings to use named subgroup expansion (eg `${mygroup}`) rather than numbered (eg `${1}`).
Also rename the "subgroup" field to "subgroup_to_replace" to make it more obvious how it works.
=> Use named subgroups exclusively

examples/templates/render/hello_jupiter/go.mod
By adding go.mod to this directory, we make it its own Go module, with its own dependencies and versions. In this case, there happen to be no dependencies, so it's unusually simple. There's no go.sum for that reason.
=> Each template should be a separate Go module

README.md, templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_include.go, templates/commands/render_action_include_test.go, templates/commands/render_action_test.go, templates/model/spec.go, templates/model/spec_test.go
This adds the `skip` field in the `include` action. The lets template developers say "include this list of directories, but omit these subdirectories/files thereunder."
The template spec YAML file is now automatically skipped. If user does `include "."`, what they really want is "include every file in the template in the output, *except for this spec.yaml*".
Also added docs, see README.md for more details on how this works. This also adds some docs that were previously missing for `as`,`strip_prefix`, and `add_prefix` options on the `include` action.
Also refactored `copyRecursive()`. It started having too many parameters, so there's now a `copyParams` struct to group them together.
Closes #55.
=> feat: allow skipping specific input files/dirs

README.md, templates/commands/render.go
The `abc templates render` command has many command line flags. Now they're documented.
Also add log entries when the temp dirs are created.
Closes #29.
=> Document CLI flags in the README

.github/workflows/lint-test.yml, README.md
Windows isn't yet in the test matrix because test currently don't pass on Windows (which is issue #70).(https://github.com/abcxyz/abc/pull/71).
This is a recreation of PR #71 which got into a stuck workflow state during a GitHub outage.
=> Run tests on linux and mac (2nd PR attempt)

README.md, templates/commands/render.go, templates/commands/render_test.go
There are no new calls to mkdir in this PR because we already have code that creates directories as needed. We just needed to remove a validation check.
Previously, we enforced that the destination dir already exists. This was intended to support the user journey where we're installing into the root of a git repo. However, a new user journey has emerged where we're installing a new directory into an existing git repo. In this case it's annoying to pre-create the directory and/or hackily precede every path in the spec file with a subdirectory name.
=> Create dest dir if nonexistent, rather than failing

t/rest_server/.github/workflows/ci.yaml, t/rest_server/main_test.go
Taken from https://github.com/abcxyz/bet-in-a-box/blob/main/.github/workflows/ci.yml, includes go lint, go test, yaml lint
=> Add CI workflow to rest_server example

t/data_migration_pipeline/spec.yaml
error reading template spec file: invalid config near line 25 column 5: field "desc" is required
=> Fix a template typo in t/data_migration_pipeline

cmd/abc/abc.go, internal/version/version.go, templates/commands/render.go, templates/commands/render_test.go
This guarantees that `abc -version` won't get out of sync with the actual release.
Also fix a trivial unrelated problem where the default log level appeared redundantly in two places and used `warning` instead of the correct `warn`.
I tried logging the version number as a debug-level log message on abc startup, but the abcxyz cli package does not allow access to flags from main(), only from subcommand Run() functions.
=> Use version from build metadata vs hardcoded

templates/commands/render.go, templates/commands/render_test.go
It turns out that the standard library already provides this function, so we don't need our own.
Also rename `diff` -> `newKey` because the value isn't semantically a diff, it's just a different string.
=> Use filepath.FromSlash instead of our own impln

go.mod, templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_include.go, templates/commands/render_action_test.go, templates/commands/render_test.go
This PR lays the groundwork for the "destination includes" feature coming in a following PR.
We add a callback to the copyRecursive function that lets the handling of each file be specified as it's crawled (overwrite or skip). In the following PR we'll add a new option to back up each file if it's being overwritten. It also informs the caller of the names of each crawled file.
Also, fix a bug found while testing this change: add the `O_TRUNC` option when overwriting a file. When overwriting a longer file with a shorter file, we were leaving some of the old file contents at the end of the file.
Also some misc cleanups:
- rename `from`->`src` and `to`->`dst` in render_action_test.go. We agreed on this renaming but missed some spots.
- factor out `copyFile()` from the anonymous function …
=> Refactor copyRecursive to add callback

cmd/abc/abc.go, cmd/abc/abc_test.go, examples/templates/render/print/spec.yaml, templates/commands/render.go
Also fix a place where os.Stdout was hardcoded into render.go. It should use the output stream provided by the cli package for testability.
=> Add tests for abc.go

.vscode/launch.json
This allows VS Code users to debug the full CLI command, rather than just debugging a _test.go file.
=> Add VS Code debug configuration

README.md, templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_include.go, templates/commands/render_action_include_test.go, templates/commands/render_action_print.go, templates/commands/render_action_print_test.go, templates/commands/render_test.go, templates/model/spec.go, templates/model/spec_test.go
Fixes #85.
To be able to pass the entire set of flags around, I factored them out of the Render struct into a new dedicated struct, `renderFlags`.
Q: Why only expose some flags? Why expose `--dest` but not `--force-overwrite`?
A: API parsimony. We should limit the things we expose to just the things which we know are useful, since we'll have to support this in the future. We can always expose more flags later.
Q: Why only expose these flags to the print action?
A: We want to avoid the temptation for template authors to be inappropriately clever. We think we've provided a single correct way to do things, and we don't want people macking weird hacks unnecessarily. We want template rendering to be deterministic, and not change in surprising ways depending on flag values.
Since we're adding a …
=> Add flags to go-template context for print action

templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_gotemplate.go, templates/commands/render_action_regexnamelookup.go, templates/commands/render_action_regexreplace.go, templates/commands/render_action_stringreplace.go, templates/commands/render_action_test.go
1. Move r.setLogEnvVars() before flag parse, so cli could correctly intake flag value
2. Add logs everywhere
example
```
INFO	commands/render.go:592	created temporary template directory at: /tmp/abc-template-copy-7745125156508404672
INFO	commands/render.go:593	copied source template github.com/abcxyz/abc.git//examples/templates/render/hello_jupiter into temporary directory /tmp/abc-template-copy-7745125156508404672
INFO	commands/render.go:346	created temporary scratch directory at: /tmp/abc-scratch-13218785992439717935
INFO	commands/render.go:393	created backup directory at my_home/.abc/backups/1689614607/2066743529
INFO	commands/render_action.go:380	backed up previous contents of main.go at my_home/.abc/backups/1689614607/2066743529/main.go
INFO	commands/render.go:604	removing all …
```
=> Add more log messages for template rendering

templates/commands/render.go, templates/commands/render_action_include.go, templates/commands/render_action_include_test.go, templates/commands/render_action_print.go, templates/commands/render_action_print_test.go, templates/commands/render_test.go
This exposes the RenderFlags struct for external use, and adds the Render.RunWithFlags method.
This is PR 1 of 3-ish that will add a test framework for templates. The goal is to (1) allow template developers to test their templates and (2) allow abc CLI developers to verify that code changes haven't broken templates.
Reviewers, all of the interesting changes are in render.go, and the rest is just changed capitalization and renaming.
=> Add an API for running Render programmatically

cmd/abc/abc.go, templates/commands/render.go, templates/commands/render_flags.go, templates/commands/render_test.go
This is a straight rename/move. No code changes.
=> cleanup: move RenderFlags to own file, rename Render to RenderCommand

templates/commands/render_action_regexreplace.go, templates/commands/render_action_regexreplace_test.go
Replacing an entire regex match worked, but replacing just a subgroup within a regex was buggy. This fixes the bug and adds some tests that would have caught the problem.
=> fix: regex replacement with subgroups

README.md, templates/commands/render.go, templates/commands/render_action_include.go, templates/commands/render_action_include_test.go, templates/commands/render_action_print.go, templates/commands/render_action_print_test.go, templates/commands/render_flags.go, templates/commands/render_test.go
This was a group decision at this week's team meeting. We think it's cleaner to have a template be unambiguously identified by its `<location>` string, rather than a (location,--spec) tuple. This simplifies the mental model for users.
So, now we always look for `spec.yaml` in the root directory of the template location that was provided by the user.
=> Remove the `--spec` flag

templates/commands/render.go
We were setting the right environment variables to configure the `logging` package, but since we never called `logging.NewFromEnv`, it had no effect.
This fixes JSON output being printed to the console unexpectedly.
This is hard to unit test, but I manually verified that the output levels and modes look good. There's no more surprise JSON output.
cc @verbanicm who noticed this problem.
=> fix: log level and mode were being ignored

templates/commands/render_action.go, templates/commands/render_action_test.go
We were returning fs.SkipDir when skipping files *and* directories, but we should have only returned it when skipping a directory. When we return SkipDir to skip a file, we accidentally were skipping the remainder of the files in the directory.
=> fix: files were incorrectly skipped

README.md, templates/commands/render.go, templates/commands/render_flags.go
This is a feature for template authors that makes it easier to understand the state of the scratch directory.
If the flag is provided, we print a recursive directory listing of the scratch directory after each step of the spec file.
This addresses part of #121. It was useful in debugging #145.
=> feat: add --debug-scratch-contents flag

templates/commands/render_action_regexnamelookup.go, templates/commands/render_action_regexnamelookup_test.go, templates/commands/render_action_regexreplace.go, templates/commands/render_action_regexreplace_test.go
Every action should process the templates in its `paths` parameter, like `paths: ['{{.input_filename}}']`. This was accidentally overlooked when I wrote these two regex actions (regex_replace, regex_name_lookup).
There's a separate issue #143 to potentially refactor this to make it cleaner and less vulnerable to oversights like this, but that's out of scope here.
Fixes #142 .
=> fix: the regex actions weren't expanding path templates

internal/version/version.go
This fixes #148. Before, we weren't outputting the version number unless it had been placed in ldflags by goreleaser.
The outputted module version includes a partial git sha, so it unambiguously identifies the code that's running.
Example output when installed with `go install`:
```
$ abc -version
abc v0.0.1-alpha6.0.20230815192907-8d9c1c1a0444 (HEAD, linux/amd64)
```
=> Output module version from buildinfo if not built by goreleaser

templates/model/spec.go, templates/model/spec_test.go, templates/model/validate.go
This is the first of several PRs implementing `for_each` (see #127). This just adds the data structures that the YAML is parsed into, and some parsing tests.
=> Add AST models for `for_each`

README.md, templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_append.go, templates/commands/render_action_append_test.go, templates/commands/render_action_gotemplate.go, templates/commands/render_action_gotemplate_test.go, templates/commands/render_action_include.go, templates/commands/render_action_include_test.go, templates/commands/render_action_print.go, templates/commands/render_action_print_test.go, templates/commands/render_action_regexnamelookup.go, templates/commands/render_action_regexnamelookup_test.go, templates/commands/render_action_regexreplace.go, templates/commands/render_action_regexreplace_test.go, templates/commands/render_action_stringreplace.go, templates/commands/render_action_stringreplace_test.go, templates/commands/render_action_test.go, templates/commands/scope.go, templates/commands/scope_test.go, templates/model/spec.go, templates/model/spec_test.go
This is one of several PRs adding the `for_each` feature (#127).
In `for_each`, we add the concept of an "key", which is the index variable of the loop that takes on a sequence of values. This means that we need a way to bring a new variable into scope for the lifetime of the for_each loop.
The solution is to do lexical scoping like in a programming language. The "body" of the for_each is its own scope, and the for_each key is only in-scope for those actions. If there's a variable of the same name in an outer scope, it is temporarily shadowed until the inner scope is done.
Perhaps controversial: the `print` action has privileged access to some flag values, by doing lookups like `{{.flags.dest}}`. This was a weird outlier, because `flags` was the only thing we exposed to users that wasn't …
=> Add hierarchical variable scopes

templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_foreach.go, templates/commands/render_action_foreach_test.go, templates/commands/render_test.go
This adds partial support for the `for_each` action (#127). This includes the core logic for running a sequence of steps over each of a list of values.
This only supports iterating over a literal YAML list of values. Future PRs will add CEL integration to iterate over a programmatically defined list.
Docs are also still missing.
=> Partial for_each support

cmd/abc/abc.go, templates/commands/render_action.go, templates/commands/test_record.go, templates/commands/test_verify.go
Boilerplate for post validation tests.
Modified an existing file to pass linter CI:
directive `//nolint:errorlint` is unused for linter "errorlint" (nolintlint)
=> Add placeholder for `abc template test` commands.

templates/commands/cel.go, templates/commands/render.go, templates/commands/render_action.go, templates/commands/render_action_include.go, templates/commands/render_action_regexnamelookup.go, templates/commands/render_action_regexreplace.go, templates/commands/render_action_regexreplace_test.go, templates/commands/render_action_test.go, templates/model/pos.go, templates/model/pos_test.go, templates/model/spec.go, templates/model/spec_test.go, templates/model/validate.go
We had two separate similar mechanisms for reporting an error along with the position in the spec.yaml where it happened. Both were overly verbose. Now there's one simple, concise way.
As a bonus we get to remove lots of nolint annotations because functions named Errorf() are exempted from the `wrapcheck` linter.
=> Clean up positional error reporting

README.md
We forgot to document this when we built it.
=> Document the include from destination feature

.github/workflows/lint-test.yml
We'll run the lint&test actions for all PRs, not just those targeting `main`.
This improves the "stacked PR" workflow where the user breaks a change into several PRs, each one "based" on the previous PR, and sends them separately for review. Before this change, only the first PR in the stack would automatically be linted&tested.
If this works sanely, we can consider making a similar change to other abcxyz repos.
=> Run presubmits on all PRs

examples/templates/render/inputs/spec.yaml, templates/commands/cel.go, templates/commands/render.go, templates/commands/render_action_foreach.go, templates/commands/render_flags.go, templates/commands/render_test.go, templates/model/spec.go, templates/model/spec_test.go
Each input in spec.yaml can now optionally have a list of "rules" (CEL predicates) to check it for validity. An example use case is to check that a given string is suitable to be used as a GCP project ID.
Partially implements #28.
Example error message:
```
input validation failed:
Input name:   my_input
Input value:  foo
Rule:         my_input.startsWith("ham")
Rule msg:     Must start with "ham"
```
We support validating multiple inputs together. For example, you could require that the combined length of two strings is less than some number, or you could require that exactly one of two inputs is non-empty. Every input is in scope in every validation function.
We also include information about the validation rules when prompting for user inputs. This will help the user input something …
=> feat: CEL validation rules for template inputs

examples/templates/render/inputs/spec.yaml, templates/commands/cel.go, templates/commands/cel_test.go
These new CEL functions are intended to be used for input validation. They validate that their input matches the expected format. This PR adds functions for validating GCP service accounts and project IDs.
Part of #39.
=> feat: custom CEL functions for matching GCP service accounts

templates/commands/cel.go, templates/commands/cel_test.go
This will be used in spec.yaml input fields to verify that the user provided a GCP project number:
For #39 .
=> Implement gcp_matches_project_number CEL func

templates/model/spec.go, templates/model/spec_test.go
We do YAML magic to detect when old-style input was provided (the `paths` field is a list of strings) and automatically parse it into new-style structs.
This is part of @kevya-google's work on supporting path objects. This provides backward compatibility with preexisting spec.yaml files.
=> Detect and handle old-style paths-as-list-of-strings

templates/commands/render/render.go, templates/commands/render/render_flags.go, templates/commands/render/render_test.go
For #39.
This adds the ability for CLI users to skip input validation if they know for sure that their input is valid. This could be useful if the template's spec.yaml contains overly-strict validation logic.
=> feat: add `--skip-input-validation` flag

templates/model/spec.go, templates/model/test.go
This is just a little cleaner and more concise.
Also add some missing doc comments.
=> Trivial one-linerization of unmarshal methods

templates/model/test.go, templates/model/test/test.go
To be consistent with other model structs, the validation logic would go in a Validate() method.
=> Move the validation logic for Test structs

README.md, examples/templates/render/for_each_dynamic/spec.yaml, examples/templates/render/for_each_hardcoded/spec.yaml, examples/templates/render/hello_jupiter/spec.yaml, examples/templates/render/inputs/spec.yaml, examples/templates/render/print/spec.yaml, t/data_migration_pipeline/spec.yaml, t/react_template/spec.yaml, t/rest_server/spec.yaml, templates/commands/render/render_test.go, templates/model/spec.go, templates/model/spec_test.go, templates/model/test.go, templates/model/test_test.go
This is the only field that's camel case, and it should be snake case for consistency with the other fields. It was a mistake in the first place for it to be capitalized differently (oops 🫤).
For backward compatibility, we'll still accept `apiVersion`, but we'll prefer `api_version`.
=> Rename apiVersion YAML field to api_version

examples/templates/render/for_each_dynamic/spec.yaml, examples/templates/render/for_each_hardcoded/spec.yaml, examples/templates/render/hello_jupiter/spec.yaml, examples/templates/render/inputs/spec.yaml, examples/templates/render/print/spec.yaml, t/data_migration_pipeline/spec.yaml, t/react_template/spec.yaml, t/rest_server/spec.yaml
This caused an outage, which is currently happening. People cannot use the existing online templates with their locally-installed abc cli. We should have bumped the schema version, which would have required people to update their abc CLI.
=> Rollback breaking apiVersion->api_version change

templates/commands/render/render_test.go, templates/model/manifest/manifest.go, templates/model/manifest/manifest_test.go, templates/model/pos.go, templates/model/spec/spec.go, templates/model/spec/spec_test.go, templates/model/test/test.go, templates/model/unmarshal.go, templates/model/validate.go
Part of #191.
These structs will represent the contents of the new "manifest" file, which contains all the information we'll need in the future to cleanly upgrade a template output.
This PR contains custom unmarshaling but not custom marshaling. That will be a separate PR.
Example manifest file:
```
api_version: 'cli.abcxyz.dev/v1alpha1'
template_location: 'github.com/abcxyz/abc.git//t/rest_server'
template_dirhash: 'h1:5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03'
inputs:
- name: 'my_input_1'
value: 'my_value_1'
- name: 'my_input_2'
value: 'my_value_2'
output_hashes:
- file: 'a/b/c.txt'
hash: 'h1:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c'
- file: 'd/e/f.txt'
hash: 'h1:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730'
```
Some of …
=> Add YAML model structs for manifest files

templates/commands/render/render_action_include.go, templates/commands/render/render_action_include_test.go, templates/model/spec/spec.go, templates/model/spec/spec_test.go
As determined with Dave, these are redundant since the `As` option is preferred.
=> Remove StripPrefix, AddPrefix params

README.md
People are finding that it's easy to miss these, leading to problems and escalations.
Closes #197
=> Make the `-sSL` flags for curl more obvious

templates/model/manifest/manifest.go, templates/model/manifest/manifest_test.go, templates/model/spec/spec.go, templates/model/spec/spec_test.go, templates/model/test/test.go, templates/model/test/test_test.go, templates/model/validate.go, templates/model/validate_test.go
We anticipate adding new features and YAML fields. When a template uses these new fields but the user is using an old binary, then there will be error about the api_version being unrecognized. This error might be confusing, so now we'll also tell the user to go update their binary.
=> Advise the user to update if api_version is unknown

templates/model/decode/decode.go, templates/model/decode/decode_test.go
I'm trying to help users be less confused when they try to use a feature that's not supported in the api_version that they're using. When a YAML file fails parsing or validation, we'll suggest that the user upgrade to the newest api_version, with one condition. We'll only make this suggestion if the file actually does parse and validate successfully under the newest api_version.
For example, suppose you try to use the new `if` feature in a YAML file whose `api_version` is `v1alpha`. The error message will say (paraphrasing) `your YAML file isn't valid, but if you change the api_version field to v1beta1 instead it will be valid.`
=> Suggest upgrading api_version when it would help

README.md
Before releasing version 0.2, we need to remove the documentation that says it's not released yet.
=> Remove "not released yet" remark on 0.2, will release soon

templates/common/exec.go, templates/common/exec_test.go, templates/common/git/git.go, templates/common/git/git_test.go
This is PR 1/N for supporting semantic-versioned templates. Eventually, we'll replace the go-getter library with our own git CLI wrapper (see internal design doc).
The operations we need to support are:
- Download a template (git clone)
- Discover what versions are available (git ls-remote); versions are git tags
=> Add git CLI wrappers for cloning and listing tags

templates/commands/goldentest/record_test.go, templates/commands/goldentest/test_funcs_test.go, templates/commands/render/action_append_test.go, templates/commands/render/action_gotemplate_test.go, templates/commands/render/action_include_test.go, templates/commands/render/action_regexnamelookup_test.go, templates/commands/render/action_regexreplace_test.go, templates/commands/render/action_stringreplace_test.go, templates/commands/render/action_test.go, templates/commands/render/render_test.go, templates/common/test_utils.go
There are a bunch of tests that deal with converting file path separators, but this can all be cleaned way up by moving it down into the helper functions that are already being used.
Also, make `WriteAll*` call `t.Fatalf` instead of returning error, to be consistent with `LoadAll*` and save boilerplate in tests.
=> Untangle tech debt re file separators in tests

templates/commands/render/action_regexreplace.go, templates/commands/render/templatesource/localsource.go, templates/commands/render/templatesource/source.go, templates/commands/render/templatesource/source_test.go
This is part of the PR series that adds semantic versioning of templates. As part of that, we're replacing the go-getter library with our own template downloader.
=> Add a sourceParser that reads a template from a local dir

templates/commands/render/templatesource/git.go, templates/commands/render/templatesource/source.go, templates/commands/render/templatesource/source_test.go
Although we're replacing go-getter with our own git integration, we still want to accept go-getter-style template source locations so we don't break our users' workflows. We do log a warning suggesting that they change to the new format though.
=> Support some go-getter URLs as template sources

templates/commands/render/templatesource/localsource.go
When I wrote the old code I wasn't aware of how to use errors.As() correctly.
=> Use errors.As over type assertion

templates/commands/render/render.go
Why? Because if the user passed --keep-temp-dirs, they definitely care about the directory paths, and we shouldn't make them set ABC_LOG_LEVEL=debug and sort through a huge pile of irrelevant logs. Also, it makes sense to "warn" the user that we're cluttering their filesystem.
=> When --keep-temp-dirs=true, log dir locations at level warn instead of debug

README.md, templates/common/fs.go
Among some other minor cleanups, there were some remaining outdated references to go-getter.
=> Trivial cleanups to README

templates/commands/render/templatesource/localsource.go
This message currently shows a warning every time someone renders a template using the go-getter location syntax. This is falsely alarming for users.
=> Decrease log severity when source is not local dir

templates/commands/render/templatesource/git.go, templates/commands/render/templatesource/git_test.go
This needs to be a particularly helpful error message because users will see this in the case where they try to use a template that's committed to main but not part of a tagged release. I recently had this happen to me and was confused for a bit.
=> Return a more helpful error when the subdirectory looks wrong

templates/commands/render/templatesource/git.go, templates/commands/render/templatesource/localsource.go, templates/commands/render/templatesource/source.go, templates/commands/render/templatesource/source_test.go
This removes the global dependency on $PWD.
- Refs https://github.com/abcxyz/abc/pull/266
=> Allow parallelizing ParseSource tests

templates/commands/render/templatesource/source_test.go
TrimPrefix was accidentally called as `TrimPrefix(prefix, input)` instead of `TrimPrefix(input, prefix)`.
=> Fix accidentally reversed arguments to TrimPrefix

templates/commands/render/render.go, templates/commands/render/render_test.go
We recently rewrote the input handling logic to make the c.flags.Input field immutable and update a different mutable map as input values were processed. However, we missed two spots that was left working the old way. This resulted in:
- inputs being ignored in the case where they were interactively entered by the user
- validation logic not seeing some inputs
=> fix: multiple input processing bugs

templates/commands/render/action_include.go, templates/commands/render/render.go, templates/commands/render/templatesource/git.go, templates/commands/render/templatesource/localsource.go, templates/commands/render/templatesource/source.go, templates/commands/render/templatesource/source_test.go, templates/common/fs.go, templates/common/git/git_test.go, templates/common/test_utils.go
A canonical template source is one that isn't tied to the machine where it's running. For example, a template source like
`github/abcxyz/abc/t/rest_server` is canonical because anyone can reference it. A template source like "/home/dave/my_unpacked_tarball" is not canonical because that directory only exists on my machine. As a complicated special case, a path like `/home/dave/git/myrepo` may or may not be canonical, depending on whether the destination is in the same git repo as the source. See the internal design doc (ping me for a link).
Also, we add a new common function `IsStatNotExist()` to factor out the common pattern of checking whether we Stat()ed a path that doesn't exist.
=> Implement "canonical template sources"

README.md, templates/commands/render/templatesource/git.go, templates/commands/render/templatesource/git_test.go, templates/common/git/git.go, templates/common/git/git_test.go
abc CLI `v0.3.0` introduced a constraint to only allowing versions with `latest` or `semver` tag. We no longer want to force the tagged semver constraint on users so this change will allow versioning with branch names, including `@main`, or long commit SHA's. Short commit SHA's are not supported and will be tried as branch name or tag.
Resolves #288
=> chore: allow versions with branch names or SHA

templates/commands/goldentest/record.go, templates/commands/render/action.go, templates/commands/render/render.go, templates/common/fs.go, templates/common/templatesource/download.go, templates/common/templatesource/git.go, templates/common/templatesource/localsource.go, templates/model/spec/v1beta1/spec.go
This includes one real bug where we returned nil instead of err in templates/model/spec/v1beta1/spec.go !
=> Fix lint found by new linters

templates/commands/render/flags.go, templates/commands/render/render.go
This should have been changed when we migrated off of go-getter, but was overlooked.
Fixes #297 .
=> Fix outdated help text and comment

.vscode/launch.json, cmd/abc/abc.go, templates/commands/goldentest/record.go, templates/commands/goldentest/test_funcs.go, templates/commands/goldentest/test_funcs_test.go, templates/commands/goldentest/verify.go, templates/model/goldentest/v1alpha1/upgrade.go, templates/model/manifest/v1alpha1/upgrade.go, templates/model/spec/v1beta1/upgrade.go
The problem was that the context.Context wasn't being passed through to all the goldentest functions.
Also remove the redundant configuration of signal handlers in goldentest/test_funcs.go. We already have these in abc.go so I think this is superfluous.
Some other minor tweaks as long as I'm touching this code:
- In the logging package, "mode" was renamed to "format". Update our constant names in abc.go accordingly.
- Use typed constants for the default log level and mode
- Fix a misleading log message related to upgrades to make it clear we're talking about model upgrades and not abc binary upgrades.
- Add a VS Code debugger config for debugging goldentest recording
=> Fix golden-test command logging in JSON format instead of text

templates/commands/goldentest/flags.go, templates/commands/goldentest/verify_test.go
This flag is documented as required, but not enforced. This PR adds enforcement and a unit test.
=> Enforce the presence of the --location flag in goldentest

templates/commands/describe/describe.go, templates/commands/render/render.go, templates/common/specutil/spec.go, templates/common/specutil/spec_test.go
The old error message was:
```
$ abc templates render .
error opening template spec: ReadFile(): open /tmp/template-copy-2622731642/spec.yaml: no such file or directory
```
The new error message is:
```
$ abc templates render .
couldn't find spec.yaml in that directory, the provided template location "." might be incorrect
```
As part of this, we refactor some duplicated code into a common package.
Also clean up some repetitive names and out-of-date comments in specutil/spec.go.
=> Give a more helpful error when the input is not a template

templates/commands/goldentest/record.go, templates/commands/goldentest/record_test.go, templates/commands/goldentest/test_funcs.go, templates/commands/goldentest/test_funcs_test.go, templates/model/goldentest/v1alpha1/goldentest_test.go
- Since we're now rendering test file in <testname>/data folder, clearTestDir is no longer needed.
- Also refactored goldentest model testing logic to only focus on goldentest yaml, leaving version and kind validation to other common logic.
=> Clearer golden test recording logic.

templates/commands/render/render.go
This should be visible at the default log level, and the default log level is Warn.
=> Change debug scratch contents to Warn

README.md, templates/commands/goldentest/flags.go, templates/commands/goldentest/record.go, templates/commands/goldentest/record_test.go, templates/commands/goldentest/test_funcs.go, templates/commands/goldentest/test_funcs_test.go, templates/commands/goldentest/verify.go, templates/commands/goldentest/verify_test.go
- Update to `abc templates golden-test record --test-name=<test_name> <location>`
- Testname is now repeatable
=> Update golden-test cmd param orders.

templates/commands/render/manifest.go, templates/commands/render/manifest_test.go, templates/commands/render/render.go, templates/common/templatesource/download.go, templates/common/templatesource/git.go, templates/common/templatesource/git_test.go, templates/common/templatesource/localsource.go, templates/common/templatesource/localsource_test.go, templates/common/templatesource/source_test.go
There was some awkwardness around passing around a Downloader object that had already been used for downloading, just for the purpose of getting some metadata about the download. This cleanup just returns the download metadata from the Download() function, and that's passed around instead.
This avoids:
- Undesirable statefulness in the Downloader
- Leaking the Downloader to places that shouldn't download
- Overly complicated tests that have to mock a Downloader despite not doing any downloading
=> Refactor clean-up of passing around canonical source

templates/common/templatesource/git.go, templates/common/templatesource/git_test.go
There was a bug here. When installing a template from a remote git repo, and the spec.yaml is in the root of the repo, then the template output would include the .git dir created by the clone operation. Nobody wants that.
=> fix: don't copy .git dir into template output

templates/commands/render/render.go
This was a leftover from an earlier time when the temp dir had a separate name generation step and creation step.
=> Remove superfluous call to MkdirAll for temp dir

.vscode/launch.json, cmd/abc/abc.go, templates/commands/render/flags.go, templates/commands/render/render.go, templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/common/flags/flags.go, templates/common/specutil/spec.go
There's no interesting upgrade logic yet. This PR just:
- factors out some flags that were formerly specific to the `render` command that are now shared with the `upgrade` command, into the `common/flags` package.
- Adds the `abc templates upgrade` common as a no-op. It's in "hidden" mode so it won't show up in the help text. It just loads the manifest file from the filesystem and does nothing with it.
- Adds usage instructions.
=> Add the skeleton of the upgrade command

templates/commands/render/render.go, templates/commands/render/render_test.go, templates/commands/upgrade/upgrade.go, templates/common/input/input.go, templates/common/input/input_test.go
This code will be needed for the `upgrade` command, so it can't live with the `render` command anymore.
This involved:
- Turning methods into plain methods. This required passing a lot more parameters around, so we create the `ResolveParams` struct to encapsulate them.
- Moving code from render.go into a new package, common/input/input.go. Along with associated tests.
=> Factor out template input handling into common package

.github/workflows/lint-test.yml
This runs in parallel with the other steps, and is fast enough that it doesn't increase the overall time-to-completion.
This is a bit of a hack until we add feature #311 to discover and run all golden-tests within a given directory.
=> Run all golden_tests during lint & test phase

.github/workflows/lint-test.yml
I realized that a lot of our path handling bugs come up on Windows, so we should take every opportunity to test there.
=> Run golden tests on all OSes, not just ubuntu

templates/common/fs.go, templates/common/render/render.go, templates/common/templatesource/localsource.go, templates/common/templatesource/source.go, templates/common/templatesource/source_test.go
These are mistakes that the user is likely to make, and we want to print a more helpful error message:
Mistake 1: the user provides the path to the spec.yaml as the template path, where they're actually supposed to provide the path to the directory containing the spec.yaml. We add a very clear error message for this case.
Mistake 2: providing some other filename instead of a directory name: we provide a warning that filenames can't be parsed as local template paths.
Before this, the error message was very confusing, just `cannot overwrite a directory with a file of the same name`.
=> Give a more helpful error if the user gives an invalid template location

.github/workflows/lint-test.yml, .github/workflows/release.yml
use latest go-test and go-lint in pkg
=> chore: use latest go-test and go-lint in pkg

templates/common/render/manifest.go, templates/common/render/manifest_test.go, templates/common/render/render_test.go, templates/common/templatesource/download.go, templates/common/templatesource/git.go, templates/common/templatesource/git_test.go, templates/common/templatesource/localsource.go, templates/common/templatesource/localsource_test.go, templates/common/templatesource/source.go, templates/model/manifest/v1alpha1/manifest.go
There's a design decision here. We're treating template location strings differently in manifest files than when we parse template locations provided by users on the command line.
- Template locations on the command line don't explicitly specify the template location type. We just try to parse it in a few different ways and see what works (i.e. is this a github URL or a local directory?)
- In manifest files, we explicitly record the template location type (either "local_git" or "remote_git"), and *don't* try to autodetect anything.
Why? There are two important differences:
- Manifest files are written and read only by programs, not people. We can pay a little cost in verbosity to avoid the ambiguity of trying to guess whether a location is a URL or a local file.
- Manifest files store …
=> Add location_type to the upgrade manifest YAML model

templates/commands/goldentest/test_funcs_test.go
By only calling DiffErrString when err!=nil, we could have some false negatives where tests pass when they shouldn't. We want to catch the case where the code-under-test neglects to return an error when it should.
=> DiffErrString() should be called unconditionally

templates/commands/goldentest/test_funcs_test.go, templates/common/builtinvar/builtin_vars.go, templates/common/render/render.go
To help golden-test authors write good tests, we want to force them to provide fake values for all the builtin vars that they use, without accidentally relying on a default value of empty string. By forcing the test authors to think through what they're testing, they'll be more likely to cover both the empty-string and non-empty-string cases.
To this, if a template is being run in a golden-test, and the template references a builtin var, and that var doesn't have an override defined in test.yaml's `builtin_vars` field, the test will fail with a message about an unknown variable.
A future PR will make the error easier to understand and obvious how to fix the test.
=> Make builtin vars only in scope if overridden

templates/common/cel_test.go, templates/common/input/input_test.go, templates/common/render/action_foreach_test.go, templates/model/spec/v1alpha1/spec_test.go, templates/model/spec/v1beta1/spec_test.go, templates/model/spec/v1beta2/spec_test.go, templates/model/spec/v1beta3/spec_test.go
- It's cleaner
- It allows double-clicking subtest names when debugging
=> Consistently use underscore for test names

.github/workflows/lint-test.yml, examples/templates/render/git_vars/spec.yaml, examples/templates/render/git_vars/testdata/golden/is_git_no_tag/data/out.txt, examples/templates/render/git_vars/testdata/golden/is_git_no_tag/test.yaml, examples/templates/render/git_vars/testdata/golden/is_git_with_tag/data/out.txt, examples/templates/render/git_vars/testdata/golden/is_git_with_tag/test.yaml, examples/templates/render/git_vars/testdata/golden/not_git/data/out.txt, examples/templates/render/git_vars/testdata/golden/not_git/test.yaml, templates/commands/goldentest/verify.go
This is a hacky workaround for #400, but doesn't fully address that.
By running `git config --global core.autocrlf false` in the CI workflow, we prevent git from mangling the line endings when checking out the golden test recorded output. See #400 for a more thorough writeup of the problem.
We also add a test for the `git_vars` example template, which exercises the fix.
=> Workaround for git mangling line-endings in golden tests

.github/workflows/notify-on-issue-and-release.yml
please merge after https://github.com/google-github-actions/send-google-chat-webhook/pull/16 is merged and new release (v0.0.2) is created.
fixes: https://github.com/abcxyz/abc/issues/402
=> feat: create notify on issue and release

templates/commands/describe/describe.go, templates/commands/goldentest/new_test_cli.go, templates/commands/goldentest/record.go, templates/commands/goldentest/test_funcs.go, templates/commands/goldentest/verify.go, templates/commands/render/render_test.go, templates/common/render/action_include_test.go, templates/common/render/render.go, templates/common/render/render_test.go, templates/common/tempdir/paths.go, templates/common/tempdir/tempremover.go, templates/common/templatesource/remote_git.go
Handling of temp dirs was slightly incorrect and ugly in several ways:
- In some places, errors were ignored when removing temp dirs
- One temp dir was created but never used
- There was a mishmash of styles, all of which were overly verbose and error prone
- Some temp dirs were not cleaned up on the error path
- os.TempDir() was being called unnecessarily, MkdirTemp() accepts `""` to default to using `/tmp`
So we renovate `TempTracker` and use it consistently.
=> Rewrite temp dir management

templates/commands/goldentest/verify_test.go
fixed part1 of #428 
add a unit test that makes sure a test without an .abc directory can still execute
=> chore: added UT to keep .gitkeep

internal/version/version.go, templates/commands/goldentest/new_test_cli.go, templates/common/render/manifest.go, templates/model/decode/decode.go, templates/model/decode/decode_test.go
Currently, it can be hard to release a new binary version because any unfinished features and api_versions will be exposed in that release. For example, we can't release a new binary version if api_version `v1beta4` is unfinished, because the new binary will put `api_version: v1beta4` in all the yaml files that it creates.
Instead, we want the ability to release a new binary version at any time, with unfinished features hidden behind an api_version that is still hidden from the public.
To do this, we mark each release struct with a boolean indicating whether it is released or not. api_versions that are under construction will not be used by official release binaries. When a release build of abc creates a yaml file, the header will use api_version=$last_officially_released_api_version, not …
=> Add the concept of unreleased api_versions

templates/model/goldentest/v1alpha1/goldentest.go, templates/model/goldentest/v1alpha1/goldentest_test.go, templates/model/goldentest/v1beta3/goldentest.go, templates/model/goldentest/v1beta3/goldentest_test.go, templates/model/goldentest/v1beta4/goldentest.go, templates/model/goldentest/v1beta4/goldentest_test.go
Before this fix, unmarshaling of test.yaml will fail if any input `value` is missing or empty-string. Empty string is a valid value for many inputs.
Fixes #447 .
=> fix: allow goldentest input values be empty

templates/model/validate.go, templates/model/validate_test.go
A nil pointer panic was observed in a dev environment with a horribly mangled spec.yaml file, the likes of which will probably never be seen again. But let's still handle it just in case.
=> Handle ValidateEach being passed a nil element

templates/commands/describe/describe_test.go, templates/commands/goldentest/new_test_cli_test.go, templates/commands/goldentest/record_test.go, templates/commands/goldentest/record_verify_test.go, templates/commands/goldentest/test_funcs_test.go, templates/commands/goldentest/verify_test.go, templates/commands/render/render_test.go, templates/common/dirhash/dirhash_test.go, templates/common/fs_test.go, templates/common/git/git_test.go, templates/common/render/action_append_test.go, templates/common/render/action_gotemplate_test.go, templates/common/render/action_include_test.go, templates/common/render/action_regexnamelookup_test.go, templates/common/render/action_regexreplace_test.go, templates/common/render/action_stringreplace_test.go, templates/common/render/action_test.go, templates/common/render/manifest_test.go, templates/common/render/render_test.go, templates/common/templatesource/localsource_test.go, templates/common/templatesource/remote_git_test.go, templates/common/templatesource/source_test.go, templates/common/templatesource/upgrade_test.go, templates/common/upgrade/upgrade_test.go, templates/testutil/fs.go
These function names were overly long and awkward. WriteAllDefaultMode became very common since it was created, and therefore deserves a shorter, cleaner name. Ditto for Read*.
There are no changes in this PR besides two changed function names and an updated comment.
=> Trivial renaming of testutil WriteAll/ReadAll

run_golden_tests.sh
Instead of running `go run` repeatedly, which takes a while even when there's nothing to rebuild, we just build the binary once and run it directly.
=> Make run_golden_tests.sh 10x faster

t/data_migration_pipeline/go.mod, t/data_migration_pipeline/go.sum, t/data_migration_pipeline/testdata/golden/basic/data/go.mod, t/data_migration_pipeline/testdata/golden/basic/data/go.sum, t/rest_server/contents/go.mod, t/rest_server/contents/go.sum, t/rest_server/testdata/golden/basic/data/go.mod, t/rest_server/testdata/golden/basic/data/go.sum
dependabot couldn't do this on its own because of golden tests expecting the template output go.mod to have the old version. So, I downloaded the patch and ran `golden-test record` to create this PR.
=> Resolve dependabot alert for protojson

templates/common/upgrade/merge.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
This is similar to how git won't let you proceed until you resolve merge conflicts. When an upgrade operation begins, we look for any `*.abcmerge_*` files that would indicate that there was a previous upgrade operation that still needs to be manually resolved. If we were to ignore this and upgrade anyway, the user would likely be incredibly confused, and that would be bad.
=> feat: detect previous unmerged files and abort upgrade

t/data_migration_pipeline/README.md, t/data_migration_pipeline/testdata/golden/basic/data/README.md
The shell blocks on this page got messed up. I suspect at some point someone's editor auto-ran `mdformat`, which tried to turn some "```shell ...```" blocks into inline "`shell ...`" blocks which don't render properly.
=> Fix markdown shell rendering

templates/common/render/action_include.go, templates/common/render/action_include_test.go, templates/common/render/action_test.go, templates/common/render/render.go
There was a bug here that we haven't actually hit, but could be important for the template upgrade logic that will build on top of this. The bug could cause files to be considered "included from destination" even when they're not. The bug arises when the same path is included multiple times with a mix of regular include and "include from destination."
The fix is just to reset the state for "included from destination" when a path is re-included.
=> fix: include-from-destination bit should be reset on re-include

templates/common/render/action.go, templates/common/render/action_test.go
There was a bug in this test case; the "wanted" error for the case where skipGlobs==true was never actually being tested.
Fixes #508 .
=> Fix "impossible condition" warning

templates/commands/goldentest/verify.go, templates/common/git/git.go, templates/common/render/render.go, templates/common/run/run.go, templates/common/run/run_test.go
I'm about to make these more complex, and common shouldn't be such a dumping ground of unrelated functionality.
There's nothing interesting in this PR, just moved code.
=> Move the exec-wrapper Run* functions into their own package

templates/common/render/action_include.go, templates/common/render/action_include_test.go, templates/common/render/render.go
This is kind of a bug, but the upgrade code isn't exposed yet, so not really. In the case where an upgrade operation executes an `include` action with `from: destination`, the file should be copied from the ultimate user-visible destination folder, not the temp dir that we're rendering into (which will just be empty).
=> Fix "include from destination" behavior in the upgrade case

go.mod, go.sum, templates/common/run/diff_test.go
Fixes #534 
The problem is that macOS 14 `diff`, which comes from freebsd, colors its output differently than GNU diff, which is common on Linux.
We didn't catch this in CI because github actions `macos-latest` uses macos 12, whose `diff` binary has no color support at all.
The fix is just to test for the presence of *any* colors rather than looking for exact color codes.
=> Fix terminal color test failure on mac 14

templates/common/render/render.go, templates/common/run/run.go, templates/common/upgrade/hash.go
These variables were renamed in a recent PR, but their string values were never updated accordingly. These aren't load-bearing, just for printing in logs and error messages.
=> Fix hashResult names

templates/common/render/action_include_test.go
This code predates the creation of simpler string-based helper for the same purpose.
We also add a single separate test that the include action preserves permissions, rather than emcumbering every subtest with ModeAndContents verbosity.
=> Remove unnecessarily verbose permissions testing

t/rest_server/contents/go.mod, t/rest_server/contents/go.sum, t/rest_server/contents/main.go, t/rest_server/testdata/golden/basic/data/go.mod, t/rest_server/testdata/golden/basic/data/go.sum, t/rest_server/testdata/golden/basic/data/main.go
Now that the std library supports routing via method: https://go.dev/blog/routing-enhancements the main reason for using Chi is no longer needed.
I removed the walk function as it's not necessary and not easily supported by the standard library.
=> Template rest_server: switch from chi to std library.

templates/commands/goldentest/record.go, templates/commands/goldentest/test_funcs.go, templates/commands/goldentest/test_funcs_test.go, templates/commands/goldentest/verify.go
Recently we added the ability for `golden-test verify` and `record` to crawl the directory tree looking for tests to process. This failed in the case where it found a template with no tests (it's valid for a template to not have tests).
The crawling logic was untested, so we add tests now.
=> Fix a bug in golden-test verify for templates without tests

README.md, templates/commands/render/flags.go, templates/common/flags/flags.go
It would be annoying for the user to have to add --git-protocol=ssh to every command line if they always use ssh.
=> Add environment variables for some common flags

templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
When an upgrade operation fails to apply a patch to an included-from-destination file, we'll ask the user to manually resolve the conflict, then re-run the upgrade operation with `--already-resolved=filename.txt` to indicate that they resolved the conflict.
=> Add a flag for patches that the user already resolved

templates/common/render/manifest.go, templates/common/render/manifest_test.go, templates/common/templatesource/download.go, templates/common/templatesource/git.go, templates/common/templatesource/localsource.go, templates/common/templatesource/localsource_test.go, templates/common/templatesource/remote_git.go, templates/common/templatesource/remote_git_test.go, templates/common/templatesource/source.go, templates/common/templatesource/upgrade.go, templates/common/templatesource/upgrade_test.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
In an upcoming PR, we need to distinguish between remote templates (e.g. from GitHub) and local templates (e.g. in some local directory). This distinction matters for the "upgrade all templates under this directory" feature, for complex reasons that probably aren't worth going into here (feel free to ask if you're interested).
As part of this, we change the DownloadMetadata.LocationType field from a string to an enum, because we want to add an IsRemote() method to LocationType. And also because this is an exported API now, and that suggests being cleaner with types.
=> Return DownloadMetadata from Upgrade()

templates/commands/goldentest/test_funcs.go, templates/common/render/action_include.go, templates/testutil/prompt.go
- Improve log messages to indicate what the test is currently trying to
do
- Make it easy to disable test timeouts so developers can debug a
failing test at a leisurely pace.
Also change "spec.yaml" to specutil.SpecFileName. We made a constant for
this so we should use it everywhere.
=> Minor tweaks to dialog test debugging

templates/common/graph/graph.go, templates/common/graph/graph_test.go
The caller wants to know the nodes involved in the cycle, not a string description of the cycle.
=> Report cycles as a data structure, not a string

templates/common/render/action_include_test.go, templates/common/templatesource/source_test.go, templates/common/templatesource/upgrade_test.go, templates/common/upgrade/upgrade_test.go, templates/testutil/cmp.go
In several places we need to discard certain parts of certain fields before comparing got vs want values in tests. This solution is much cleaner than the previous hacks, and is used in the upcoming "upgrade all" feature.
=> Use cmp Transformers and FilterPath for fuzzy comparison

templates/common/upgrade/upgradeall.go
This is one chunk of the "upgrade all" feature that upgrades every template installation underneath a given directory. It's broken up to avoid an oversized PR.
This logic is about crawling manifest files and using them to infer dependencies between template installations. This is needed for the case where a template T1 outputs another template T2. When upgrading, we want to upgrade all usages of T1 before T2, because the upgrade of T1 may alter the template definition T2.
=> Add `crawlManifests()` and `depGraph()`

templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/commands/upgrade/upgrade_test.go, templates/common/flags/flags.go, templates/common/graph/graph.go, templates/common/templatesource/remote_git.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go, templates/common/upgrade/upgradeall.go
With this PR, users can just run "abc upgrade" and we'll find all the template installations under the current directory and upgrade all of them. The user no longer has to point to a manifest file, or even know what a manifest file is.
It's still missing some tests, which I'll add in a future PR. This one is already huge.
This is alpha quality at best. It probably has many critical bugs. But I've been working on this for months and it's time to get something committed.
=> Add "upgrade all" feature

templates/common/graph/graph.go, templates/common/graph/graph_test.go
This makes the asymptotic runtime worse, but we don't care so much right now given the anticipated sizes of our graphs.
This is important for the "upgrade all" algorithm. We want to attempt upgrades in the same order every time, especially when the user restarts an "upgrade all" operation partway through after resolving a merge conflict.
=> Sort neighbors to make topological sort have stable output

templates/commands/goldentest/record.go, templates/commands/render/render.go, templates/common/fs.go, templates/common/fs_test.go, templates/common/render/action_include.go, templates/common/render/render.go, templates/common/render/render_test.go
In the just submitted PR #582, there was a bug: if the template outputted any files that already existed in the destination, the render operation would fail. However, in --manifest-only mode, this is fine and expected. These files *should* already exist.
Renamed CopyParams.Overwrite to CopyParams.AllowExisting to reflect that it's now used in situations where an overwrite is not actually occurring; now it's just a flag to indicate "don't fail if the file exists in the destination, which doesn't necessarily imply that it will be overwritten."
=> fix: --manifest-only was failing if unrelated files exist in the dest

.vscode/launch.json, templates/common/upgrade/upgrade_test.go, templates/common/upgrade/upgradeall.go
When a template fails to upgrade due to conflicts between the template and local edits, we should stop upgrading any further templates until the merge conflicts are resolved.
It used to work this way, but broke in a refactor by accident. I added a test to prevent regressing on this behavior again.
=> fix: "upgrade all" should halt on merge conflict

templates/commands/upgrade/upgrade.go, templates/commands/upgrade/upgrade_test.go, templates/common/upgrade/upgrade.go
When the upgrade operation is interrupted due to a merge conflict that needs to be manually resolved, we instruct the user how to continue the upgrade by running a command. Before this PR, we attempted to print the exact command to run to continue the upgrade. But I realized that this approach was flawed because we need to print all the flag values that might be needed (like --version). These flags may or may not have been provided by the user in their upgrade command.
That would have been too complex. So the new solution in this PR is to tell the user to re-run their previous upgrade command with a certain flag added, without attempting to provide the full set of flags.
=> Adjust the suggested commands to continue an upgrade

templates/common/fs.go, templates/common/fs_test.go, templates/common/git/git.go, templates/common/git/git_test.go, templates/common/run/run.go, templates/common/templatesource/localsource.go, templates/common/templatesource/localsource_test.go, templates/common/templatesource/remote_git.go, templates/common/templatesource/remote_git_test.go, templates/common/templatesource/source_test.go, templates/common/templatesource/upgrade_test.go, templates/testutil/fs.go
Fixes #324 .
Before this, downloading the `latest` template version from a git repo involved two steps: querying the list of tags in the remote repo using `git ls-remote`, then running `git clone --branch` to get a particular template without downloading unnecessary history. This design was intended to avoid unnecessarily large downloads. However, there were some issues:
- Opening a connection and authenticating twice is slow for SSH connections.
- For users of physical security keys, two touches are needed.
So now we just do a plain `git clone` (no `--branch`), and then `git checkout` the requested version.
Also, we remove `findSymlinks()` and instead implement anti-symlink protection as a feature on `CopyRecursive` (this is the `ForbidSymlink` change).
A kevya and drevell …
=> Clone entire repos instead of only the requested version

templates/commands/upgrade/flags.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
Building on #589, now we actually use the upgrade_track field that was added to the manifest to determine which branch to upgrade to. This is intended to support the use case where if a user installs from a branch, then future template upgrades will be pulled from that branch.
=> Use the upgrade_track from the manifest

templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go, templates/common/upgrade/upgradeall.go
When there is a "patch reversal conflict" (which happens when there's a merge conflict during upgrade on a file that was modified in place), then the user must run `abc upgrade --resume-from=some/manifest.yaml` to resume the upgrade. This PR implements the feature; the flag existed before but was unused.
=> Implement the `upgrade --resume-from` feature

templates/commands/upgrade/flags.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go, templates/common/upgrade/upgradeall.go
This code runs when recovering from merge conflicts. After a merge conflict is resolved, the user runs `abc upgrade <directory> --resume-from=some-manifest.yaml --already-resolved=<list-of-files>`. In the case where there are multiple template installations to be upgraded, the `--already-resolved` flag should only apply to the first one, and later upgrades should be attempted from scratch.
The implementation is just one line, and the rest is just test updates and reorganization.
=> Finish implementing --resume-from/--already-resolved

templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/common/templatesource/source.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go, templates/common/upgrade/upgradeall.go
If a template is rendered from a "canonical" location, such as a github repo, then we store the source of template in the manifest. Future template upgrades will check that location for new versions of the template. But when the template is installed from a non-canonical location, like `abc render ~/alice-silly-temp-dir`, then there's no location stored in the manifest to be checked for updates.
This PR adds the "--template-location" flag to the abc upgrade command to provide a template location to upgrade to, overriding the manifest. So somebody else can come along later and do something like `abc upgrade --template-location github.com/me/myrepo/mytemplate` or `abc upgrade --template-location ~/bob-silly-temp-dir`, even if the manifest doesn't have a stored location.
=> Allow templates to be upgraded even when installed from a random local dir

templates/commands/upgrade/upgrade_test.go, templates/common/upgrade/merge.go, templates/common/upgrade/upgrade_test.go
Before this PR, when there was a conflict between a local edit and an edited file in the upstream template, abc would rename the user's local file to something like `foo.abcmerge_locally_edited` and drop the template's edited version of the file as `foo.abcmerge_new_from_template`.
However, after using `abc` as a user, I think a better user experience is to leave the user's filename unchanged. The sensible workflow for a user who's facing a merge conflict is to diff their local file with the incoming file and selectively incorporate changes from the upstream template file. These files don't have equal standing from the user's point of view: the user wants to keep what they have and carefully vet and integrate the upstream changes. This PR makes that change.
=> For certain conflict types, leave local filenames unchanged

templates/common/input/input.go, templates/common/render/render_test.go, templates/common/upgrade/upgrade.go
There was a bug in the way unknown inputs were handled. They would be correctly ignored for the purposes of rendering the template, but would still appear in the manifest. This didn't cause serious problems, but was confusing and gross; a manifest should not save any inputs that weren't actually passed to the template during rendering.
=> fix: ignored inputs should not appear in manifest

templates/commands/render/flags.go, templates/commands/render/render.go, templates/commands/render/render_test.go, templates/common/render/manifest.go, templates/common/render/render.go, templates/common/render/render_test.go, templates/common/templatesource/download.go
This lets the user specify what branch they want to track for upgrades. The default is still the old behavior, which is to make an educated guess (if the user installed from `mybranch` then track that, otherwise upgrade from the latest semver release).
=> Add the --upgrade-channel flag

templates/model/manifest/v1alpha1/manifest.go, templates/model/manifest/v1alpha1/manifest_test.go
This should never have been enforced. It's perfectly legal for a template input value to be empty string.
=> Allow empty string as a manifest input value

templates/commands/goldentest/new_test_cli_test.go, templates/commands/render/render_test.go, templates/commands/upgrade/upgrade_test.go, templates/common/input/input.go, templates/common/render/render_test.go, templates/common/templatesource/remote_git.go, templates/common/upgrade/upgrade_test.go, templates/testutil/cmp.go, templates/testutil/prompt/prompt.go
This tests an edge case where:
1. A template is installed that has no inputs.
2. The template is updated to add an input that has a default value
3. We run an upgrade
4. The user should be prompted for a value for the new input; the default value should not silently be used.
I thought I saw this last week in my manual testing, but the test passes without changing the logic, so I may have been mistaken.
This change involves some refactoring and test util updates because this is the first time that we've tested prompting logic at the library layer (`common/*`), rather than the Command layer (`commands/*`) which wraps the library.
=> Test prompting during upgrade when a new input is added with a default

templates/commands/goldentest/new_test_cli.go, templates/commands/goldentest/new_test_flags.go, templates/commands/goldentest/test_funcs.go, templates/commands/render/flags.go, templates/commands/render/render.go, templates/commands/render/render_test.go, templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/common/flags/flags.go, templates/common/input/input.go, templates/common/render/render.go, templates/common/render/render_test.go, templates/common/upgrade/upgrade.go
This avoids a specific poor user experience. Suppose the user runs `abc upgrade` (without --prompt), which is a very reasonable thing to do. Suppose the upgraded version of the template has a new input with a default value for that input. It would be bad for abc to just silently use the default value for that new input; technically you could argue that the user should have used the --prompt flag if they wanted a chance to override the default, but that would be a footgun and we can't expect users to be that diligent. So we'll reject the current operation and ask the user to clarify their intent with either --prompt or --accept-defaults.
=> Add --accept-defaults flag, and error when user intent is unclear

templates/commands/goldentest/test_funcs.go, templates/commands/render/render.go, templates/commands/upgrade/upgrade.go, templates/commands/upgrade/upgrade_test.go, templates/common/fs_test.go, templates/common/git/git_test.go, templates/common/input/input.go, templates/common/render/render.go, templates/common/render/render_test.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go, templates/testutil/fs.go
If the user wanted to override any input values during an upgrade, or provide a value for a newly-introduced template flag, their `--input=foo=bar` CLI flag was simply ignored. :upside-down-face:
We also add a test for the case where upgrade override flags come from a YAML file.
=> fix: --input flags to upgrade were being ignored

templates/common/upgrade/hash.go, templates/common/upgrade/merge.go, templates/common/upgrade/upgrade_test.go
In the case where:
- A template outputs a file
- The user edits that file
- We upgrade to a template that also changes that same file to the exact same contents as the user's local modified copy
There should be no conflict, because the locally edited copy and the new template "agree" on the desired contents of the file.
This was observed when testing upgrades in infra-gcp and finding spurious merge conflicts asking me to resolve files that were identical.
Also, add a file Close() that was missing 🙃
=> Handle edited-but-equal merge conflict more intelligently

templates/commands/upgrade/upgrade.go
This will be released soon, and in the meantime the lack of tab-completion is annoying.
=> Unhide the `upgrade` subcommand

templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/common/render/render.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
This flag forces the upgrade command to proceed even if the the installed template version is already the latest version. This is useful for:
- Forcing the manifest to be rewritten, perhaps to change the --template-location or --upgrade-channel values
- Re-rendering a template with different inputs using `--input=foo=bar`
=> Add the --even-if-up-to-date flag to `upgrade`

.github/workflows/notify-on-issue-and-release.yml
I don't think we need this. It was here for debugging purposes (I assume).
=> chore: remove workflow dispatch trigger

templates/commands/render/flags.go, templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/common/flags/flags.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
This flag already existed on the `render` command, I just moved it to `common` and referenced it from the `upgrade` command now. This flag controls the `upgrade_channel` field on the manifest field that is output during rendering/upgrading.
=> Add --upgrade-channel flag to upgrade command

templates/common/render/render_test.go
Since these hashes change when we modify a test, we'll just ignore them so test authors don't have to provide a valid hash in the "want" manifest. This is better than updating these hashes whenever we modify or create a test case.
=> Ignore the manifest Dirhash and Hash fields in test assertions

cmd/abc/abc_test.go, templates/commands/goldentest/test_funcs.go, templates/commands/goldentest/test_funcs_test.go, templates/commands/render/flags.go, templates/commands/render/render.go, templates/commands/render/render_test.go, templates/commands/upgrade/upgrade_test.go, templates/common/render/render.go, templates/common/render/render_test.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
Going forward, we want render operations to default to producing a manifest, so they're upgradeable later. Therefore, in the Render() library API, we want to invert to sense of the Manifest bool to SkipManifest so that the default value of false does the desirable default behavior.
This is technically part of an exported API that shouldn't be changed, but since there's only one non-CLI user of this, and he's on our team, we'll allow it to change.
To be consistent with the above, the command line flag also changes from --manifest to --skip-manifest. This is also a backwards-incompatible change, but since the flag is documented as experimental, we'll allow it.
We also update a bunch of tests to assert on the produced manifests.
=> Remove Manifest option in favor of SkipManifest

examples/templates/render/hello_jupiter/spec.yaml, examples/templates/render/hello_jupiter/testdata/golden/example_test/data/go.mod
The hello_jupiter file contained a go.mod file that was supposed to part of the template output, but it was never mentioned in the spec file and therefore was not actually used.
The fix is to include all files by wildcard. This requires updating the api_version to a version where wildcards are supported (v1beta6 is the latest).
We also ran `abc golden-test record` to update the recorded golden-test output with the new file.
=> fix: go.mod file should be included in template output

templates/common/functional.go, templates/common/templatesource/upgrade.go, templates/common/templatesource/upgrade_test.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
There was a bug in the case where we do `abc upgrade --version foo` to upgrade (or downgrade) to a specific version. In that case, the `upgrade_channel` field in the new manifest would be empty. The desired behavior is for the new manifest to have an upgrade_channel field equal to --upgrade-channel (if provided) or just inherit the upgrade_channel field from the old manifest.
The `FlagUpgradeChannel` struct field is renamed to `UpgradeChannel` because now it doesn't always come from a flag.
=> fix: the manifest upgrade_channel field was sometimes omitted

templates/common/upgrade/upgradeall.go
This is an uninteresting refactor of the code that loads the manifests to be upgraded and sorts them. The main idea is that we're taking code out of UpgradeAll() and moving it into a new subroutine, `manifestsToUpgrade()`.
This is to prepare for an upcoming feature that adds filtering of manifests to be upgraded.
=> Refactor manifest loading in UpgradeAll()

templates/commands/goldentest/test_funcs.go, templates/commands/render/render_test.go, templates/commands/upgrade/flags.go, templates/commands/upgrade/upgrade.go, templates/common/cel.go, templates/common/render/render_test.go, templates/common/specutil/spec.go, templates/common/upgrade/filter.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go, templates/common/upgrade/upgradeall.go, templates/model/decode/decode.go, templates/model/decode/decode_test.go
To support users with lots of template installations, we add the `abc upgrade --manifest-filter` flag. This will limit upgrades to only those template installations whose manifest passes the filter. The filter is provided by the user as a CEL expression.
The CEL expression has access to the fields of the manifest YAML file under the same field names as they appear in the manifest.
Example: upgrade all installations of the template `github.com/foo/bar`:
abc upgrade --manifest-filter='template_location ==
"github.com/foo/bar"'
Example: upgrade all installations whose `deployment_name` input has the value `foo`:
abc upgrade --manifest-filter='inputs.exists(item, item.name == "deployment_name" && item.value == "foo")'
Example: upgrade all installations that touched the file `a/b/c.txt` …
=> Add the --manifest-filter flag to `upgrade` with CEL filtering

cmd/abc/abc.go
The deadline was being applied before the program ran, which caused it to time out almost every run.
=> Fix runtime metrics timeout issue

.github/workflows/release.yml
GitHub will return lexigraphically the most recent tag if there are multiple for the same commit, which can break when doing a release after a prerelease (example: https://github.com/abcxyz/abc/actions/runs/10601630744). This hopefully will fix it.
Using feature from https://github.com/goreleaser/goreleaser/pull/1327
=> Properly set current tag when multiple tags exist for same commit

templates/model/spec/v1beta6/spec.go, templates/model/spec/v1beta6/spec_test.go, templates/model/spec/v1beta6/upgrade.go
This was an oversight by me when I created the v1beta6 api_version. I
forgot to replace `package v1beta4` with `package v1beta6` in this
directory.
=> Fix package name v1beta4 -> v1beta6

templates/common/render/render.go, templates/common/render/render_test.go, templates/common/upgrade/upgrade.go, templates/common/upgrade/upgrade_test.go
The old behavior was to noop in the case where the upstream template hasn't changed.
The new behavior is to noop in the case where the upstream template hasn't changed, AND the inputs to the template haven't changed. This includes all possible sources of inputs.
Of course this noop'ing can be overwritten with --continue-if-current to still force the upgrade operation to run.
=> Return AlreadyUpToDate if the user inputs haven't changed

t/nextjs_react_template/contents/package-lock.json, t/nextjs_react_template/contents/package.json, t/react_template/package-lock.json, t/react_template/testdata/golden/basic/data/package-lock.json
Updates goldens to allow tests to pass after dependabot updates
Original PR: https://github.com/abcxyz/abc/pull/663
This change was created by creating a new branch from the original
(dependabot/npm_and_yarn/t/nextjs_react_template/contents/npm_and_yarn-2d360efc95).
Goldens were then updated by running `abc golden-test record`.
**Original PR message:**
Bumps the npm_and_yarn group with 4 updates in the /t/nextjs_react_template/contents directory: [next](https://github.com/vercel/next.js), [@babel/runtime](https://github.com/babel/babel/tree/HEAD/packages/babel-runtime), [cookie](https://github.com/jshttp/cookie) and [@auth0/nextjs-auth0](https://github.com/auth0/nextjs-auth0).
Bumps the npm_and_yarn group with 1 update in the /t/react_template directory: …
=> original: [chore(deps): bump the npm_and_yarn group across 2 directories with 4 updates] and update golden tests
